name: .NET Core

on:
  push:
    branches: [ master, develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-18.04, ubuntu-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore --force-evaluate --no-cache --verbosity normal Demo.Exchange.sln
    - name: Build
      run: dotnet build --configuration Release --no-restore --force Demo.Exchange.sln
    - name: Test
      run: dotnet test --no-restore --verbosity normal Demo.Exchange.sln
